FROM alpine:3.8

RUN apk add --no-cache freeradius freeradius-eap freeradius-ldap openssl

COPY radiusd.conf clients.conf /etc/raddb/
COPY eap /etc/raddb/mods-available
COPY ldap /etc/raddb/mods-available
COPY site /etc/raddb/sites-available
COPY inner-tunnel /etc/raddb/sites-available
COPY users /etc/raddb/mods-config/files/authorize

RUN rm /etc/raddb/sites-enabled/* && \
    rm -rf /etc/raddb/certs && \
    ln -s /etc/raddb/mods-available/ldap /etc/raddb/mods-enabled/ldap && \
    ln -s /etc/raddb/sites-available/site /etc/raddb/sites-enabled/site && \
    ln -s /etc/raddb/sites-available/inner-tunnel /etc/raddb/sites-enabled/inner-tunnel && \
    mkdir /tmp/radiusd && \
    chown radius:radius /tmp/radiusd

COPY server.crt server.key ca.crt dh.pem /etc/raddb/certs/
RUN chown radius:radius /etc/raddb/certs/* \
    && chmod 400 /etc/raddb/certs/*

RUN chgrp -R radius /etc/raddb/

EXPOSE 1812/udp
USER radius

ENTRYPOINT ["/usr/sbin/radiusd"]
CMD ["-X", "-f"]
